name: dragid10/renovate-bot
on:
  push:
    branches:
    - main
  pull_request:
  schedule:
  - cron: "0 1 * * *"
env:
  RENOVATE_TOKEN: "${{ secrets.RENOVATE_TOKEN }}"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.13.1'
    - run: |
        # Run Renovate
        
        # Install NVM
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
        nvm install --lts; npm i -g npm@latest

        # in-between stuff
        eval $(gimme stable)
        npm i -g renovate

        # Check Go version
        go version

        # Profit?
        renovate;
